FROM node:20-alpine

WORKDIR /app

# Copy monorepo package definitions
COPY package*.json ./
COPY packages/frontend/package*.json ./packages/frontend/

RUN npm install

COPY packages/frontend ./packages/frontend

WORKDIR /app/packages/frontend

EXPOSE 5173

CMD ["npx", "vite", "--host", "0.0.0.0", "--port", "5173"]
