export const barangays = [
  "Annafunan East",
  "Annafunan West",
  "Atulayan Norte",
  "Atulayan Sur",
  "Bagay",
  "Buntun",
  "Caggay",
  "Capatan",
  "Carig Norte",
  "Carig Sur",
  "Caritan Centro",
  "Caritan Norte",
  "Caritan Sur",
  "Cataggaman Nuevo",
  "Cataggaman Pardo",
  "Cataggaman Viejo",
  "Centro 01 (Bagumbayan)",
  "Centro 02",
  "Centro 03",
  "Centro 04",
  "Centro 05 (Bagumbayan)",
  "Centro 06",
  "Centro 07",
  "Centro 08",
  "Centro 09 (Bagumbayan)",
  "Centro 10 (Riverside)",
  "Centro 11 (Balzain East)",
  "Centro 12 (Balzain West)",
  "Dadda",
  "Gosi Norte",
  "Gosi Sur",
  "Larion Alto",
  "Larion Bajo",
  "Leonarda",
  "Libag Norte",
  "Libag Sur",
  "Linao East",
  "Linao Norte",
  "Linao West",
  "Namabbalan Norte",
  "Namabbalan Sur",
  "Pallua Norte",
  "Pallua Sur",
  "Pengue-Ruyu",
  "San Gabriel",
  "Tagga",
  "Tanza",
  "Ugac Norte",
  "Ugac Sur"
]; 